server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
  api-docs:
    path: /v3/api-docs
  api:
    title: Playlist API
    description: Playlist API
    version: 1.0

spring:
  application:
    name: quipux-prueba
  datasource:
    url: jdbc:h2:mem:quipux
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

